stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - scripts/preprocess.py
      - data/raw/housing.csv
    params:
      - preprocess.test_size
      - preprocess.random_state
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - data/processed/scaler.pkl

  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - data/processed/train.csv
    params:
      - train.model_type
      - train.random_state
      - train.test_size
    outs:
      - models/best_model.pkl
      - models/feature_importance.png

  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - scripts/evaluate.py
      - data/processed/test.csv
      - models/best_model.pkl
    metrics:
      - metrics.json:
          cache: false
    plots:
      - plots/:
          cache: false