preprocess:
  test_size: 0.2
  random_state: 42

train:
  model_type: "random_forest"  # Options: random_forest, gradient_boosting, linear
  random_state: 42
  test_size: 0.2

models:
  random_forest:
    n_estimators: 100
    max_depth: 10
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
  linear:
    alpha: 0.1